chore(dal): Adding integration tests for creating attribute funcs for props and sockets
systeminit/si pull request #3563
Opened 2024-04-11 18:07 UTC by stack72

2024-04-11 18:24 UTC, nickgerace requested changes

2024-04-11 18:24 UTC, nickgerace commented on lib/dal/src/schema/variant.rs
> +        }
(this is why I requested changes)

2024-04-13 04:40 UTC, stack72 commented on lib/dal/tests/integration_test/func/authoring/create_func.rs
> +// }
:ok

2024-04-13 04:41 UTC, stack72 commented on lib/dal/src/func/authoring/create.rs
>                              ));
I have left this for now - but I want to have a conversation about it soon :)

2024-04-13 04:44 UTC, stack72 commented
bors try

2024-04-13 04:53 UTC, stack72 commented
bors merge

2024-04-13 04:59 UTC, merged